USE odbo;

CREATE TABLE IF NOT EXISTS members(
	id VARCHAR (20) PRIMARY KEY,
	passwd VARCHAR (20),
	name VARCHAR (10),
	birth VARCHAR (10),
	gender VARCHAR (4),
	email VARCHAR (50),
	signuptime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	);
	